# Application of Harmonized Clusters

## Description

In this application we want will take a look at how pollution levels evolved in Norway over time. If we were to naively use use the shape files from two different time periods and measured the local pollution levels within administrative units, we would not be able to compare the pollution levels across time, as the underlying boundaries were subject to change.

However, if we harmonize the administrative units across time we can directly compare all units as their definitions remain stable.

### Data:

-   **Administrative Units:** Statistic Norway ([SSB](https://www.ssb.no/klass/klassifikasjoner/1)) publishes the valid unit identifiers and changes to these identifiers. This will be handled by [NGeoTrack](https://laurincurschellas.github.io/NGeoTrack)
-   **Shape Files:** Official Shape Files of Norwegian Administrative Units are published by [Geonorge](https://www.geonorge.no/)
-   **Pollution Data:** We will use satellite-derived concentrations of PM$_{2.5}$ published by the Washington University in St. Luis (Annual and Monthly Mean PM$_{2.5}$ ($\mu g/m^3$) at $0.01^{\circ}$x$0.01^{\circ}$) [here](https://sites.wustl.edu/acag/datasets/surface-pm2-5/)

## Harmonize the Grunnkrets
```{r}
library(devtools)
library(dplyr)

devtools::install_github("https://github.com/LaurinCurschellas/NGeoTrack")
library(NGeoTrack) 

# Download the Changes and Status of Grunnkrets (BSU) Identifiers in chosen Period
chg_bsu <- gather_change(type = "grunnkrets", from = 1998, to = 2022)
stat_bsu <- status_quo(type = "grunnkrets", from = 1998, to = 2022) 

df_key <- EtE_changes(df_status = stat_bsu, df_change = chg_bsu, from = 1998, to = 2022) 

```

